### ISSUE TITLE
Create a Methodology for  Rename of a Package

### ISSUE THREAD

**Issue by confused-Techie** [confused-Techie/atom-backend#46]
In `./src/handlers/package_handlers.js` `postPackagesVersion()` there intends to be a way to publish a package while renaming it.

But as of now there is no defined methodology on our end of how to handle such a rename, and confirm that this is renaming the correct package.

Discussion of this issue can be opened here, or a solution can be brought up via PR.

**Comment by Digitalone1** [comment]
@confused-Techie  I'm looking at this and there are some things not clear.

- Where does `pack` come from? Maybe you mean `packJSON`? https://github.com/confused-Techie/atom-backend/blob/cb28d039ac7a3f131cab43e68e37fb58dafd1d50/src/handlers/package_handler.js#L573
- So we have to add the new version, but at least we have to retrive the `version` key. Where do we get it? From the request object or the `packJSON`?
- Same as for the license column since it cannot be NULL in the [database](https://github.com/confused-Techie/atom-backend/blob/main/scripts/database/create_versions_table.sql).
- We retrieve the `tag` from the request? What is its purpose?

**Comment by confused-Techie** [comment]
@Digitalone1 for this, yes `pack` should be `packJSON` good catch.

The version key should be retrieved from `packJSON` as that should be the exact `package.json` in the repository as it is currently. So the version could be pulled from there, and would suggest we use the version in `package.json` as long as it matches the tag. Or we could ignore the tag matching and publish whatever version we wanted in the `package.json`. Otherwise as for the `tag` it's the Git Tag for the version we would want to create.

But the original docs don't seem to mention how it's used. Since they say explicitly that the `version` key in the `package.json` is used. So not sure where the `tag` actually factors in.

But for more context [here](https://flight-manual.atom.io/atom-server-side-apis/sections/atom-package-server-api/#creating-a-new-package-version) is the original docs.

**Comment by confused-Techie** [comment]
@Digitalone1 as for the `pack` error I'll go ahead and fix that now. And ensure that endpoint currently fails with a `NotSupported` due to discussion over on [Discord](https://discord.com/channels/992103415163396136/992110095641088001/1044750499821400115), looks like it might be best to push our beta stuff to prod for now to resolve some other issues that are effecting users.

**Comment by Digitalone1** [comment]
@confused-Techie I think this can be closed.

**Comment by confused-Techie** [comment]
> @confused-Techie I think this can be closed.

Yeah good call here. Thanks for reminding me
