### ISSUE TITLE
Exponential and polynomial backtracking

### ISSUE THREAD

**Issue by Digitalone1** [confused-Techie/atom-backend#53]
I don't know why the regex I proposed was flagged by codacy as `exponential and polynomial backtracking`.

At least I suppose it's like that since @confused-Techie changed it. https://github.com/confused-Techie/atom-backend/commit/f24202e1dafa562a3e5d2d278ad4893fbef5b0c3

Anyway the current one it's still flagged the same.

**Comment by Digitalone1** [comment]
@confused-Techie please test the following one:

```js
let db_url_reg = /postgres:\/\/(?=([^@\s]+))\1@(?=([^:\s]+))\2:(\d+)\/(?=([^\/\s]+))\4/;
```

Let's see if reproducing the atomic groups with javascript is of any help. [Test](https://regex101.com/r/bjl8ZI/1).

**Comment by confused-Techie** [comment]
Thanks for the help on this one. And you're right I tried playing around with that to get it to be safer, but didn't have luck at the time. I'll try to put this in when I can otherwise feel free to make a PR, if I lag to much as I'm currently on vacation

**Comment by Digitalone1** [comment]
No problem, this week I'm pretty busy on my work so I cannot do much for the backed, but I'll hope to return on it soon.

Regarding the regex, the problem is the javascript engine not having support for atomic groups and possessive quantifiers that avoid backtracking.

Developers for web applications are forced to use the standard engine, but maybe we can use an external library/module which support an advanced regex engine with no backtracking at all? It's worth to take a look at it when we have time.

**Comment by Digitalone1** [comment]
Does this seem to be resolved? Which was the solution?

**Comment by confused-Techie** [comment]
> Does this seem to be resolved? Which was the solution?

It isn't just yet. Seems that some changes made to the codacy config stopped it from getting reported. But I still want to look into an external engine like you mentioned. Especially considering how often regex is used here

**Comment by Digitalone1** [comment]
There's this one: https://github.com/slevithan/xregexp

Isn't there a search page for NodeJS packages? Maybe there's something even better.

**Comment by confused-Techie** [comment]
While I appreciate the efforts on this one @Digitalone1, because this issue was only reported temporarily in Codacy, and has since not been reported via any of the other code scanning techniques used on the codebase, we will consider it a false positive on Codacy's side. 

While I am still excited about the idea of using an external engine for Regex, we may have to postpone that for the version 2 release. As I'm really hoping to get us to v1 as soon as we possibly can.

I'll go ahead and add this one to our roadmap, unless it's something you really wanted to pursue in the meantime. Otherwise we can get to it when we have more time to do so
