### ISSUE TITLE
Info on development

### ISSUE THREAD

**Issue by Digitalone1** [confused-Techie/atom-backend#6]
- Which are the limitations for search queries? I though to limit them to a maximum of 50 characters, but there should be another limitation. Maybe converting all non word characters as space?
- Where can I see which are the properties of `packages` objects? Could be an hint to make a sort algorithm.
- Package pointers are very difficult to understand. If you could explain hare the steps to make a new package and set its pointer, I could help in the remaining unfinished methods.

**Comment by confused-Techie** [comment]
I'll be happy to give a much more thorough  write up after work today, but to give some quick pointers, a search length limitation is a good idea. But other than that I'm not sure what method was originally used, or what we want to use here, so there's definitely some ideas on how to go about it. 

But a quick glance at the schema for the package objects is available on the [overview](https://github.com/confused-Techie/atom-community-server-backend-JS/blob/main/docs/overview.md) docs. Some additional research into how the search seemed to previously work is available on the old [Golang Repo](https://github.com/confused-Techie/atom-community-server-backend/blob/main/DEV_docs/search.txt). But of course this doesn't need to match that exactly.

**Comment by confused-Techie** [comment]
@Digitalone1 to further explain the idea of package pointers though:

Reading through the transformations that can happen to a package, the package name can be changed, and the owner can be transferred, meaning neither the owner nor package name are reliable unique identifiers. Plus once a package is made, even if the name is changed, the old name will still always point to the original package. To not break links or documentation presumably. Additionally, having every single package in a single file would be bad practice for so much data. So what could be done is when a package is published, generate a UUIDv4 ID, completely unique, and use that as the file name for the package. Then in the package pointer file, the package name becomes a key, pointing to the unique filename, then if the name is ever changed, just add the new name pointing to the same unique filename, This way the old name still links to the same package, as well as the new name pointing to the same package. I'm planning to use the [UUID](https://www.npmjs.com/package/uuid) NPM package to accomplish the generation of IDs. 

One important note about publishing a package, is we also need some way to verify that the whoever is publishing the package on atom also is a contributor/owner of the repo on Github. Me previous comment links to my overview.md doc where I talk about some ways we could do this. Or assuming how it was done before. And that is really the big stopper for creating and testing that functionality.

Finally about the packages properties. The package file will contain what we can colloquially call 'Package Object Full', but in almost every api endpoint will only return the 'Package Object Short'. Only the package details endpoint will return a 'Package Object Full'. Really the 'Prune' method of `collection.js` will need to be rewritten to modify the 'Package Object Full' and convert it into the 'Package Object Short'. Additionally the raw 'Package Object' will contain some extra data that is never returned to the end user, and instead used only server side. Which lets call that just 'Package Object' or even 'Server Package Object'. The schema linked previously has a more basic example, but I will go ahead and upload the actual file being used for reference that was archived from the Atom.io package repository.

I hope this information helps with understanding better, but also its my weekend off work, so I should have more time to flesh out this much needed behavior of the backend. Let me know if theres anything you'd like me to clear up. 😀

**Comment by confused-Techie** [comment]
Also just realizing I didn't even talk about search in my previous comment, and being honest was fleshing out the naming scheme for packages while writing. So to clarify on naming:

* `Server Package Object`: The package object that is read directly from the filesystem, containing server side data to be pruned, as well as containing the `Package Object Full`
* `Package Object Full`: Only ever given to the end user during a 'Details' API Query.
* `Package Object Short`: The Package Object returned in every other API Query and is the standard package object users would be interacting with.

As for Search:

I wrote more as I investigated how the previous search worked in my Golang Repo linked above. But the atom-community core maintainers and I decided this was not a priority to replicate, and instead focus on having something that works.

But one thing is clear that searching works by searching the name of the package. Which is logical behavior that I think we should keep, rather than attempting to search through the readme or other aspects of the package. But that can absolutely be changed later on if wanted.

As for the name, we should set all requirements around that. Looking at the [NPM Name in Package.json file specs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json) we get some good info that I wasn't even aware of until reading more thoroughly right now:

> Some Rules:
> * The name must be less than or equal to 214 characters. This includes the scope for scoped packages.
> * The names of scoped packages can begin with a dot or an underscore. This is not permitted without a scope.
> * New packages must not have uppercase letters in the name.
> * The name ends up being part of a URL, an argument on the command line, and a folder name. Therefore, the name can't contain any non-URL-safe characters.

Unfortunately the [current Atom Docs](https://flight-manual.atom.io/hacking-atom/sections/publishing/) make no remarks about naming conventions.

But we know we aren't going to be working with scoped modules or anything like that. And something I found while archiving all current packages is that some packages are even published with just an emoji as a name. Meaning some conversion happens before sending a package name to us, to convert it to URL safe characters. Now this behavior may be something we want to change, but for the time being we want to do our best to create something equivalent to what exists. 

From this we can take our few rules:

* Less than or equal to 214 characters.
* Cannot begin with a dot or underscore.
* Cannot contain a space.
* A big want would be only URL safe characters, but Atom is already not doing this. 

So since we know that this is the end data we are searching, there's a few ways that can be handled. 

I do like the idea of taking anything with a space, and inserting a '-'/dash, and in the search method dashes will be handled as word separators. 

The search query should additionally be decoded from URL safe characters using something like [decodeURI()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) before any transformations take place. We can additionally throw out any search query that contains a dot or underscore as the first character. And one thing I will work on today is sanitizing the search query to ensure its not malicious. 

If there's any other ideas that you have towards how to handle search please feel free to let me know, as this is something I'm currently working on.

**Comment by Digitalone1** [comment]
I will give a look at what you pointed out.

I saw also you made lots of changes to the code.

Anyway the first thing that comes to my mind is to make a regex to validate package names.

**Comment by Digitalone1** [comment]
I think this can be closed.

**Comment by confused-Techie** [comment]
> I think this can be closed.

Good call, most of this info is probably outdated anyway
